### List notifications
GET http://localhost:3000/notifications

### Create a new notification
POST http://localhost:3000/notifications
Content-Type: application/json

{
    "recipientId": "{{$guid}}",
    "content": "testing now :D",
    "category": "fewfewfew"
}