### List notifications
GET http://localhost:3000/notifications

### Create a new notification
POST http://localhost:3000/notifications
Content-Type: application/json

{
    "recipientId": "{{$guid}}",
    "content": "testing now :D",
    "category": "fewfewfew"
}

### Cancel a notification by id
PATCH http://localhost:3000/notifications/6740fddd-9d4b-4af9-9156-676dfd3345a6/cancel

### Read a notification by id
PATCH http://localhost:3000/notifications/6740fddd-9d4b-4af9-9156-676dfd3345a6/read

### Unread a notification by id
PATCH http://localhost:3000/notifications/6740fddd-9d4b-4af9-9156-676dfd3345a6/unread

### Count from recipient id
GET http://localhost:3000/notifications/count/from/6de5e00a-9cf5-4f7c-982e-0e879fcdf306